-- ClickHouse DDL: plm_service_route
-- Source: Oracle plm_service_route (PLM Service/Production Route Configuration)
-- Generated by: oracle-to-ch skill

CREATE TABLE plm.plm_service_route ON CLUSTER ch_cluster
(
    route_id       String,
    part_id        String,
    fab_cd         String,
    service_flow   String,
    service_stage  String,
    seq_no         Int16,
    create_dt      DateTime
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/plm_service_route', '{replica}')
ORDER BY (route_id);

GRANT SELECT ON plm.plm_service_route TO plm_pdmpi_ch ON CLUSTER ch_cluster;
