-- ClickHouse DDL: plm_mtn_log
-- Source: Oracle plm_mtn_log (PLM Engineering Maintenance and Change Log)
-- Generated by: oracle-to-ch skill

CREATE TABLE plm.plm_mtn_log ON CLUSTER ch_cluster
(
    log_id       String,
    part_id      String,
    mtn_user     String,
    action_type  String,
    log_desc     Nullable(String),
    create_dt    DateTime
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/plm_mtn_log', '{replica}')
ORDER BY (log_id);

GRANT SELECT ON plm.plm_mtn_log TO plm_pdmpi_ch ON CLUSTER ch_cluster;
