-- ClickHouse DDL: plm_part
-- Source: Oracle plm_part (PLM Part/Product Master)
-- Generated by: oracle-to-ch skill

CREATE TABLE plm.plm_part ON CLUSTER ch_cluster
(
    part_id       String,
    cust_cd       String,
    tech_cd       Nullable(String),
    part_desc     Nullable(String),
    cust_id       String,
    cust_part_no  Nullable(String),
    status        Nullable(String),
    create_dt     DateTime,
    update_dt     DateTime
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/plm_part', '{replica}')
ORDER BY (part_id);

GRANT SELECT ON plm.plm_part TO plm_pdmpi_ch ON CLUSTER ch_cluster;
